resolution: 700.0
resolution_view: 1000.0
map_size: 8.0
margin: 0.5
max_ticks: 250
timestep: 0.1
robot_radius: 0.15
goal_radius: 0.5
min_humans: 1
max_humans: 3
min_tables: 1
max_tables: 1
human_threshold: 0.4
reach_reward: 1.0
outofmap_reward: -0.5
maxticks_reward: -0.3
alive_reward: -0.003
collision_reward: -0.5
discomfort_distance: 0.5
discomfort_penalty_factor: 0.005
max_advance: 1.4
human_speed: 0.3
max_rotation: 1.57079632679  # Equivalent to np.pi / 2
milliseconds: 30
debug: 0
human_debug: False
robot_view: True
robot_size: 0.15
human_size: 0.15
goal_size: 0.25
table_size: [1.0, 0.6]
seed: 42
