name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt
    - name: Run tests
      run: |
        python -m unittest discover tests


Explanation of the Workflow:

    Trigger Events:
        The workflow runs on pushes and pull requests to the main branch.
    Jobs:
        Job build: Tests the code across multiple Python versions (3.7 to 3.10).
    Steps:
        Checkout Repository: Uses actions/checkout@v3 to clone the repository.
        Set Up Python: Uses actions/setup-python@v4 to set up the specified Python version.
        Install Dependencies: Upgrades pip, installs the package in editable mode, and installs dependencies from requirements.txt.
        Run Tests: Executes the test suite using unittest.
